from pydantic import BaseModel, Field, ConfigDict, EmailStr
from typing import List


class MessageSchema(BaseModel):
    """
    Schema for a full message record (GET /{id}, response of POST /).
    All fields are required in responses.
    """
    model_config = ConfigDict(populate_by_name=True)

    messageid: int = Field(..., ge=1, description="Message ID, minimum 1")
    name: str = Field(..., min_length=1, description="Sender name")
    email: EmailStr = Field(..., min_length=1, description="Sender email")
    phone: str = Field(..., min_length=11, max_length=21, description="Sender phone number")
    subject: str = Field(..., min_length=5, max_length=100, description="Message subject")
    description: str = Field(..., min_length=20, max_length=2000, description="Message body")


class CreateMessageRequestSchema(BaseModel):
    """
    Schema for creating a new message (POST /).
    All fields are required except messageid (auto-generated by API).
    """
    model_config = ConfigDict(populate_by_name=True)

    name: str = Field(..., min_length=1, description="Sender name")
    email: EmailStr = Field(..., description="Sender email")
    phone: str = Field(..., min_length=11, max_length=21, description="Sender phone number")
    subject: str = Field(..., min_length=5, max_length=100, description="Message subject")
    description: str = Field(..., min_length=20, max_length=2000, description="Message body")


class MessageSummarySchema(BaseModel):
    """
    Schema for message summary in list response (GET /).
    """
    model_config = ConfigDict(populate_by_name=True)

    id: int = Field(..., description="Message ID")
    name: str = Field(..., description="Sender name")
    subject: str = Field(..., description="Message subject")
    read: bool = Field(..., description="Read status")


class MessagesResponseSchema(BaseModel):
    """
    Schema for response containing a list of message summaries (GET /).
    """
    messages: List[MessageSummarySchema]


class CountSchema(BaseModel):
    """
    Schema for message count response (GET /count).
    """
    count: int = Field(..., description="Total message count")