from enum import Enum


class AllureTag(str, Enum):
    AUTH = "AUTH"
    BOOKING = "BOOKING"
    ROOM = "ROOM"
    MESSAGE = "MESSAGE"
    BRANDING = "BRANDING"
    REPORT = "REPORT"
    HEALTH = "HEALTH"

    GET_ENTITY = "GET_ENTITY"
    GET_ENTITIES = "GET_ENTITIES"
    CREATE_ENTITY = "CREATE_ENTITY"
    UPDATE_ENTITY = "UPDATE_ENTITY"
    DELETE_ENTITY = "DELETE_ENTITY"
    VALIDATE_ENTITY = "VALIDATE_ENTITY"
